# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Python Blacken
      # You may pin to the exact commit or the version.
      # uses: piotrpawlaczek/python-blacken@00da49d5262ea8408aa006873de629fef9fc9dd1
      uses: piotrpawlaczek/python-blacken@v20.8b1
      with:
        # File or directory to run black on.
        path: . # optional, default is .
        # The number of characters allowed per line.
        line-length: 81 # optional, default is 81

    - name: Coveralls Python
      # You may pin to the exact commit or the version.
      # uses: AndreMiras/coveralls-python-action@f5fd5c309b39d01599fb92c72d4f7409ea78aec9
      uses: AndreMiras/coveralls-python-action@v20201129
      with:
        # The `GITHUB_TOKEN` or `COVERALLS_REPO_TOKEN`.
        github-token: # optional, default is ${{ github.token }}
        # Set to true if you are using parallel jobs, then use `parallel-finished: true` for the last action.
        parallel: # optional
        # Set to true for the last action when using `parallel: true`.
        parallel-finished: # optional
        # The name of a sub-directory in which the coverage files are to be found.
        base-path: # optional
        # A description of the current job used in connection with parallel.
        flag-name: # optional
        # Set to `true` to increase logger verbosity.
        debug: true # optional

    - name: python-isort
      # You may pin to the exact commit or the version.
      # uses: isort/isort-action@245468f11b1fda7916b9127e07af532df40286d3
      uses: isort/isort-action@v0.1.0
      with:
        # Version of isort to use
        isortVersion: # optional, default is
        # files or directories to sort
        sortPaths: . # optional, default is .
        # isort configuration options
        configuration: # optional, default is --check-only --diff
        # path(s) to requirements files that should be installed to properly configure third-party imports
        requirementsFiles: # optional, default is

    - name: Python Safety Check
      # You may pin to the exact commit or the version.
      # uses: aufdenpunkt/python-safety-check@d5468d88a766a647545a256f118b216833f91088
      uses: aufdenpunkt/python-safety-check@v1.0.5
      with:
        # Optional Safety script parameters. (e.g. --ignore=1234 or -i 1234)
        safety_args: # optional, default is
        # Set true to scan required python packages without installing them.
        scan_requirements_file_only: true # optional, default is false

    - name: run .travis.yml
      uses: ktomk/run-travis-yml@v1.7.0
      with:
        file: .travis.yml
        steps: |
          install
          script
        allow-failure: false
#        env:
