name: CryptoSuite

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
#    Setup our container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 pytest black isort
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#   Code beautification
    - name: Analysing the code with pylint
      run: |
        pylint `find . -name "*.py" -not -path "./.venv/*" | xargs` --exit-zero
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: applying black
      run: |
        black .
    - name: apply isort
      run: |
        isort --recursive --check-only .
#   Unittests
    - name: run unittests with pytest
      run: |
        pytest