name: CryptoSuite

on:
  push:
# Should run on every (new) branch push to our repository

  pull_request:
# Targetting specific branches within our repository
    branches:
      - main
      - staging

jobs:
  build:
#    Setup our container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install all dependencies
      run: |
        python -m pip install --upgrade pip
        for r in requirements*.txt; do pip install -r $r; done
#   Code beautification
    - name: Analysing the code with pylint
      run: |
        # always exit with a 0 return code (or the pipeline will not continue)
        pylint `find . -name "*.py" -not -path "./.venv/*" | xargs` --exit-zero
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: applying black
      run: |
        black -v .
    - name: applying isort
      run: |
        isort --check-only --diff .
#   Unittests
    - name: running unittests with pytest
      run: |
        pytest -v -rsx
